### ISSUE TITLE
ReplayId missing from zmq JSON data

### ISSUE THREAD

**Issue by christerk** [SanityResort/FFBStats#1]
With the asynchronous data delivery of zmq, the JSON dice statistics should include information on which replayId the stats correspond to. I'm attaching a diff file with code changes that adds this information to the JSON payload.

[FFBStats-replayId.txt](https://github.com/SanityResort/FFBStats/files/310447/FFBStats-replayId.txt)

**Comment by SanityResort** [comment]
Added replayId.
